#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push sandorturanszky/projects:server-express
docker push sandorturanszky/projects:server-express-nginx
